- hosts: custom
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/local/bin/python

  tasks:
    - name: Test asset connection
      ssh_ping:
        login_host: "{{ jms_asset.address }}"
        login_port: "{{ jms_asset.port }}"
        login_user: "{{ jms_account.username }}"
        login_password: "{{ jms_account.secret }}"
      register: ping_info

    - name: Change asset password
      custom_user:
        login_user: "{{ jms_account.username }}"
        login_password: "{{ jms_account.secret }}"
        login_host: "{{ jms_asset.address }}"
        login_port: "{{ jms_asset.port }}"
        name: "{{ account.username }}"
        password: "{{ account.secret }}"
        commands: "{{ jms_asset.commands }}"
        first_conn_delay_time: "{{ first_conn_delay_time }}"
      when: ping_info is succeeded
      register: change_info

    - name: Verify password
      ssh_ping:
        login_user: "{{ account.username }}"
        login_password: "{{ account.secret }}"
        login_host: "{{ jms_asset.address }}"
        login_port: "{{ jms_asset.port }}"
      when:
        - ping_info is succeeded
        - change_info is succeeded
